#!/usr/bin/env python3

#
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "TRAEFIK_HOST",
        "TRAEFIK_HTTP2HTTPS",
        "TRAEFIK_LETS_ENCRYPT",
        "LIVESYNC_DATABASE",
    ]:
    agent.set_env(evar, original_environment[evar])

# AD sync settings exist since 0.3.0
for evar in [
        "LIVESYNC_AD_DOMAIN",
        "LIVESYNC_AD_GROUP",
        "LIVESYNC_AD_NESTED",
    ]:
    agent.set_env(evar, original_environment.get(evar, ""))

agent.dump_env()
